import Script from "next/script";
import type { Metadata } from "next";
import "./globals.css";
import ClientWrapper from "./components/ClientWrapper";
import StarCanvas from "./components/background/StarBackground";

export const metadata: Metadata = {
  title: "MDR_Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* Google Analytics - à rendre en premier */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-J2WJ9P98FB"
          strategy="afterInteractive"
        />
        <Script id="ga-init" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag() { dataLayer.push(arguments); }
            gtag('js', new Date());
            gtag('config', 'G-J2WJ9P98FB');
          `}
        </Script>
      </head>
      <body className="bg-[#030014] antialiased">
        <StarCanvas />
        <ClientWrapper>
        {children}
        </ClientWrapper>
      </body>
    </html>
  );
}
